// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyecto_nicol.Data;

#nullable disable

namespace proyecto_nicol.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("proyecto_nicol.Models.USUARIOMODEMN", b =>
                {
                    b.Property<int>("Asuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Asuario_Id"));

                    b.Property<string>("Usuario_Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Asuario_Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
